variables:
  CLUSTER_NAME: ec2-catalyst-cluster-ci
  CLUSTER_PROFILE_NAME: ec2-catalyst-cluster-profile-ci
  CLUSTER_CONFIG_NAME: ec2-catalyst-cluster-config-ci
  BOOKING_IMAGE_NAME: registry.gitlab.com/tw-catalyst/booking/bookingapi:$CI_COMMIT_SHA

stages:
  - test
  - build
  - build-image
  - deploy-integration

test:
  image: gradle:5.3.0-jdk11
  stage: test
  script:
    - ./gradlew test
  artifacts:
    expire_in: 1 week
    paths:
      - build
      - .gradle

build:
  image: gradle:5.3.0-jdk11
  stage: build
  script: ./gradlew --build-cache bootjar
  artifacts:
    expire_in: 1 week
    paths:
      - build
      - .gradle

docker-build:
  image: docker:latest
  stage: build-image
  services:
    - docker:dind
  environment:
    name: integration
  script:
    - export BOOKING_IMAGE=$BOOKING_IMAGE_NAME-$CI_ENVIRONMENT_SLUG
    - echo $BOOKING_IMAGE
    - docker -v login -u gitlab-ci-token -p $GITLAB_REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t $BOOKING_IMAGE . --no-cache
    - docker push $BOOKING_IMAGE

deploy:
  image: registry.gitlab.com/gitlab-org/cloud-deploy
  stage: deploy-integration
  environment:
    name: integration
  script:
    - export BOOKING_IMAGE=$BOOKING_IMAGE_NAME-$CI_ENVIRONMENT_SLUG
    - echo $BOOKING_IMAGE
    - ./deploy.sh $BOOKING_IMAGE