variables:
  CLUSTER_NAME: ec2-catalyst-cluster-ci
  CLUSTER_PROFILE_NAME: ec2-catalyst-cluster-profile-ci
  CLUSTER_CONFIG_NAME: ec2-catalyst-cluster-config-ci
  BOOKING_IMAGE_NAME: registry.gitlab.com/tw-catalyst/booking/bookingapi
  POSTGRES_IMAGE_NAME: registry.gitlab.com/tw-catalyst/booking/postgres

stages:
  - test
  - build
  - build-image
  - deploy-integration
  - promote-staging
  - deploy-staging

test:
  image: gradle:5.3.0-jdk11
  stage: test
  script:
    - ./gradlew test
  artifacts:
    expire_in: 1 week
    paths:
      - build
      - .gradle

build:
  image: gradle:5.3.0-jdk11
  stage: build
  script: ./gradlew --build-cache bootjar
  artifacts:
    expire_in: 1 week
    paths:
      - build
      - .gradle

docker-build:
  image: docker:latest
  stage: build-image
  services:
    - docker:dind
  environment:
    name: integration
  script:
    - export BOOKING_IMAGE=$BOOKING_IMAGE_NAME:$CI_COMMIT_SHA-$CI_ENVIRONMENT_SLUG
    - export POSTGRES_IMAGE=$POSTGRES_IMAGE_NAME:$CI_COMMIT_SHA-$CI_ENVIRONMENT_SLUG
    - echo "image info - $BOOKING_IMAGE $POSTGRES_IMAGE"
    - docker -v login -u gitlab-ci-token -p $GITLAB_REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t $BOOKING_IMAGE . --no-cache
    - docker pull $POSTGRES_IMAGE_NAME
    - docker tag $POSTGRES_IMAGE_NAME $POSTGRES_IMAGE
    - docker push $BOOKING_IMAGE
    - docker push $POSTGRES_IMAGE

deploy-integration:
  image: registry.gitlab.com/gitlab-org/cloud-deploy
  stage: deploy-integration
  environment:
    name: integration
  script:
    - echo "image info - $BOOKING_IMAGE_NAME $POSTGRES_IMAGE_NAME $CI_ENVIRONMENT_SLUG $CI_COMMIT_SHA"
    - ./deploy.sh $BOOKING_IMAGE_NAME $POSTGRES_IMAGE_NAME $CI_COMMIT_SHA $CI_ENVIRONMENT_SLUG

promote-staging:
  image: docker:latest
  stage: promote-staging
  when: manual
  services:
    - docker:dind
  environment:
    name: staging
  script:
    - export BOOKING_IMAGE=$BOOKING_IMAGE_NAME:$CI_COMMIT_SHA-integration
    - export POSTGRES_IMAGE=$POSTGRES_IMAGE_NAME:$CI_COMMIT_SHA-integration
    - echo "pomoting images - $BOOKING_IMAGE $POSTGRES_IMAGE"
    - docker -v login -u gitlab-ci-token -p $GITLAB_REGISTRY_PASSWORD registry.gitlab.com
    - docker pull $BOOKING_IMAGE
    - docker pull $POSTGRES_IMAGE
    - docker tag $POSTGRES_IMAGE_NAME:$CI_COMMIT_SHA-$CI_ENVIRONMENT_SLUG $POSTGRES_IMAGE
    - docker tag $BOOKING_IMAGE_NAME:$CI_COMMIT_SHA-$CI_ENVIRONMENT_SLUG $BOOKING_IMAGE
    - docker push $BOOKING_IMAGE
    - docker push $POSTGRES_IMAGE

deploy-staging:
  image: registry.gitlab.com/gitlab-org/cloud-deploy
  stage: deploy-staging
  environment:
    name: staging
  when: manual
  script:
    - echo "image info - $BOOKING_IMAGE_NAME $POSTGRES_IMAGE_NAME $CI_ENVIRONMENT_SLUG $CI_COMMIT_SHA"
    - ./deploy.sh $BOOKING_IMAGE_NAME $POSTGRES_IMAGE_NAME $CI_COMMIT_SHA $CI_ENVIRONMENT_SLUG
