stages:
  - test
  - build

test:
  image: gradle:5.3.0-jdk11
  stage: test
  script:
    - ./gradlew test
  artifacts:
    expire_in: 1 week
    reports:
      junit: build/test-results/test/TEST-*.xml
    paths:
      - build
      - .gradle

build:
  image: gradle:5.3.0-jdk11
  stage: build
  script: ./gradlew --build-cache bootjar
  artifacts:
    paths:
      - build
      - .gradle

