stages:
  - test
  - build

test:
  image: gradle:5.3.0-jdk11
  stage: test
  script:
    - ./gradlew test jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html | grep -o 'Total[^%]*%'
  artifacts:
    paths:
      - build
      - .gradle

build:
  image: gradle:5.3.0-jdk11
  stage: build
  script: ./gradlew --build-cache bootjar
  artifacts:
    paths:
      - build
      - .gradle

