stages:
  - test
  - build
  - deploy

test:
  image: gradle:5.3.0-jdk11
  stage: test
  script:
    - ./gradlew test
  artifacts:
    expire_in: 1 week
    paths:
      - build
      - .gradle

build:
  image: gradle:5.3.0-jdk11
  stage: build
  script: ./gradlew --build-cache bootjar
  artifacts:
    expire_in: 1 week
    paths:
      - build
      - .gradle

variables:
  CLUSTER_NAME: ec2-catalyst-cluster-ci
  CLUSTER_PROFILE_NAME: ec2-catalyst-cluster-profile-ci
  CLUSTER_CONFIG_NAME: ec2-catalyst-cluster-config-ci

deploy:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - ecs-cli configure --cluster $CLUSTER_NAME --default-launch-type EC2 --config-name $CLUSTER_CONFIG_NAME --region ap-south-1
    - ecs-cli configure profile --access-key $AWS_ACCESS_KEY --secret-key $AWS_SECRET_KEY --profile-name $CLUSTER_PROFILE_NAME
    - ecs-cli up --keypair catalyst --capability-iam --size 1 --instance-type t2.medium --cluster-config $CLUSTER_CONFIG_NAME --ecs-profile $CLUSTER_PROFILE_NAME --force
    - ecs-cli registry-creds up ./creds_input_file.yml --role-name catalystSecretsExecutionRoleCI
    - rm -rf ecs-registry-creds_*.yml
    - ecs-cli compose --cluster-config $CLUSTER_CONFIG_NAME --ecs-profile $CLUSTER_PROFILE_NAME up --create-log-groups
    - ecs-cli compose down --cluster-config $CLUSTER_CONFIG_NAME --ecs-profile $CLUSTER_PROFILE_NAME
    - ecs-cli compose service up --cluster-config $CLUSTER_CONFIG_NAME --ecs-profile $CLUSTER_PROFILE_NAME
    - ecs-cli ps --cluster-config $CLUSTER_CONFIG_NAME --ecs-profile $CLUSTER_PROFILE_NAME
    - ecs-cli compose service ps --cluster-config $CLUSTER_CONFIG_NAME --ecs-profile $CLUSTER_PROFILE_NAME