version: '3.0'
services:
  db:
    image: "${POSTGRES_IMAGE}"
    ports:
      - "${HOST_DB_PORT}:5432"
    environment:
      - POSTGRES_DB=bookingengine
      - POSTGRES_USER=bookingengine
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      driver: "awslogs"
      options:
        awslogs-create-group: "true"
        awslogs-region: "ap-south-1"
        awslogs-group: "catalyst-log-group"
        awslogs-stream-prefix: "${ENVIRONMENT}-catalyst"

  web:
    image: "${BOOKING_IMAGE}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - UI_HOST=${UI_HOST}
    healthcheck:
      test: ["CMD-SHELL", "/bin/bash", "/healthcheck.sh", "localhost", "${BACKEND_PORT}", "${VERSION}"]
      interval: 10s
      timeout: 30s
      retries: 3
    links:
      - db
    ports:
      - "${BACKEND_PORT}:8080"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-south-1"
        awslogs-create-group: "true"
        awslogs-group: "catalyst-log-group"
        awslogs-stream-prefix: "${ENVIRONMENT}-catalyst"