version: '3.0'
services:
  db:
    image: "${POSTGRES_IMAGE}"
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=bookingengine
      - POSTGRES_USER=bookingengine
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      driver: "awslogs"
      options:
        awslogs-create-group: "true"
        awslogs-region: "ap-south-1"
        awslogs-group: "catalyst-log-group"
        awslogs-stream-prefix: "catalyst"

  web:
    image: "${BOOKING_IMAGE}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    links:
      - db
    ports:
      - "${BACKEND_PORT}:8080"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-south-1"
        awslogs-create-group: "true"
        awslogs-group: "catalyst-log-group"
        awslogs-stream-prefix: "catalyst"