version: '3.0'
services:
  db:
    image: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bookingengine
      - POSTGRES_USER=bookingengine
      - POSTGRES_PASSWORD=postgres

  web:
    image: booking
    ports:
      - "8080:8080"