spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/bookingengine
    username: bookingengine
    password: ${POSTGRES_PASSWORD}
logging:
  level:
    root: INFO
application:
  uiHost: http://localhost:3000
