spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/bookingengine
    username: bookingengine
    password: ${POSTGRES_PASSWORD}
logging:
  level:
    root: INFO