spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingengine
    username: bookingengine
    password: postgres
logging:
  level:
    root: INFO