spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingengine
    username: bookingengine
    password: postgres
logging:
  level:
    root: INFO
application:
  uiHost: http://localhost:3000
  movieServiceHost: http://ec2-13-234-32-0.ap-south-1.compute.amazonaws.com:4567/
  paymentServiceHost: https://tw-mock-credit-service.herokuapp.com/payments

